---
title: "R Markdown Template_FA24"
author: "Fang Bian"
date: "`r Sys.Date()`"
output: word_document
---
## clean R environment 
```{r}
rm(list = ls(all=TRUE))
graphics.off()
shell("cls")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Text 

This is an example of R Markdown document.  
You can insert an R code chunk  
1. Using the RStudio toolbar (the Insert button)  
2. Keyboard shortcut Ctrl + Alt + I ( Cmd + Option + I on macOS)  
3. End a line with two spaces to start a new paragraph.

```{r, include=FALSE}
library(ggplot2)
library(datasets) 
library(MASS)
library(dplyr)
```
```{r, out.width="60%"}
# install.packages("datasets")
# install.packages("ggplot2")
# install.packages("MASS")
# install.packages("dplyr")

View(iris)
mydata <- iris
head(mydata)
str(mydata)

# histogram 
hist(mydata$Sepal.Length)
```

# sub-setting with "[]" and "=="

```{r, out.width="60%", fig.align = 'left', fig.cap="This is a histogram."}
# sub-setting with "[]" and "=="
attach(mydata)
hist(Sepal.Length [Species == "setosa"])
detach(mydata)
```


## Don't forget to click "Knit"

# END