---
title: "R Markdown Template_FA24"
author: "Yahriel Salinas-Reyes"
date: "`r Sys.Date()`"
output: word_document
---
## clean R environment 
```{r}
rm(list = ls(all=TRUE))
graphics.off()
shell("cls")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Text 
TEST


```{r, include=FALSE}

library(readxl)
library(here)
library(epiR)
library(MASS)
library(nnet)
library(car)
library(PairedData)
library(tidyverse)
library(ggplot2)
library(pwr)
library(FSA)
library(ggpubr)
library(rstatix)
library(datarium)
library(emmeans)
library(sjstats)
library(lme4)
library(lmerTest)
library(MuMIn)
library(forcats)

library(readxl)  
library(tidyverse)  
library(dplyr)  
library(ggplot2)  
library(pwr)  
library(ggpubr)  
library(rstatix)  
library(datarium)  
library(emmeans)  
library(sjstats)  
library(lme4)  
library(lmerTest)  
library(MuMIn)  
library(dplyr)  
library(forcats)  
```

# sub-setting with "[]" and "=="

```{r, out.width="60%", fig.align = 'left', fig.cap="This is a histogram."}
# sub-setting with "[]" and "=="
attach(mydata)
hist(Sepal.Length [Species == "setosa"])
detach(mydata)
```


## Don't forget to click "Knit"

# END





















